replicaCount: 1

image:
  pactImageRepository: pactfoundation/pact-broker
  pactImageTag: 2.32.0-2
  pullPolicy: IfNotPresent

service:
  name: pact-broker
  type: ClusterIP
  externalPort: 80
  internalPort: 9292
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"

resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10
